balance_blinder = ["0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"]
balance_committed_hash = ["41", "44", "32", "211", "51", "140", "174", "73", "220", "192", "201", "121", "81", "223", "172", "98", "19", "68", "252", "173", "236", "156", "2", "243", "213", "66", "63", "182", "101", "91", "204", "222"]
balance_committed_part = "123456789012"
