[package]
name = "stwo-circuit"
version.workspace = true
edition.workspace = true

[dependencies]
stwo.workspace = true
stwo-constraint-framework.workspace = true
smol-macros.workspace = true
macro_rules_attribute.workspace = true
num-traits.workspace = true
serde.workspace = true
itertools.workspace = true
tracing.workspace = true